export type YoutubePlaylistVideo = {
      order: number;
        videoId: string;
          title: string;
            description: string;
              publishedAt: string | null;
                thumbnailUrl: string;
                  url: string;
                  };

                  type YouTubePlaylistItem = {
                    snippet?: {
                        title?: string;
                            description?: string;
                                publishedAt?: string;
                                    resourceId?: { videoId?: string };
                                        thumbnails?: Record<string, { url: string; width?: number; height?: number }>;
                                          };
                                          };

                                          type YouTubeErrorPayload = {
                                            error?: {
                                                code?: number;
                                                    message?: string;
                                                        status?: string;
                                                          };
                                                          };

                                                          export function extractYoutubePlaylistId(input?: string | null) {
                                                            const value = input?.trim();
                                                              if (!value) return '';

                                                                try {
                                                                    const url = new URL(value);
                                                                        const list = url.searchParams.get('list');
                                                                            if (list) return list.trim();

                                                                                const pathMatch = url.pathname.match(/playlist\/([^/?#]+)/i);
                                                                                    if (pathMatch?.[1]) return pathMatch[1].trim();
                                                                                      } catch {
                                                                                          // Düz playlist ID girilmiş olabilir.
                                                                                            }

                                                                                              const directMatch = value.match(/[a-zA-Z0-9_-]{8,}/);
                                                                                                return directMatch?.[0] ?? '';
                                                                                                }

                                                                                                function getBestThumbnail(item: YouTubePlaylistItem) {
                                                                                                  const thumbnails = item.snippet?.thumbnails ?? {};

                                                                                                    return (
                                                                                                        thumbnails.maxres?.url ||
                                                                                                            thumbnails.standard?.url ||
                                                                                                                thumbnails.high?.url ||
                                                                                                                    thumbnails.medium?.url ||
                                                                                                                        thumbnails.default?.url ||
                                                                                                                            ''
                                                                                                                              );
                                                                                                                              }

                                                                                                                              function youtubeErrorMessage(status: number, payload?: YouTubeErrorPayload | null) {
                                                                                                                                const providerMessage = payload?.error?.message;

                                                                                                                                  if (status === 400) {
                                                                                                                                      return providerMessage
                                                                                                                                            ? `YouTube playlist isteği geçersiz (400): ${providerMessage}`
                                                                                                                                                  : 'YouTube playlist isteği geçersiz (400). Playlist ID veya URL kontrol et.';
                                                                                                                                                    }

                                                                                                                                                      if (status === 401 || status === 403) {
                                                                                                                                                          return providerMessage
                                                                                                                                                                ? `YouTube API key reddedildi (${status}): ${providerMessage}`
                                                                                                                                                                      : `YouTube API key reddedildi (${status}). Vercel/Codespaces YOUTUBE_API_KEY değerini kontrol et.`;
                                                                                                                                                                        }

                                                                                                                                                                          if (status === 404) {
                                                                                                                                                                              return 'YouTube playlist bulunamadı (404). Playlist gizli, silinmiş veya ID hatalı olabilir.';
                                                                                                                                                                                }

                                                                                                                                                                                  if (status === 429) {
                                                                                                                                                                                      return 'YouTube API limitine takıldı (429). Biraz sonra tekrar dene.';
                                                                                                                                                                                        }

                                                                                                                                                                                          return providerMessage
                                                                                                                                                                                              ? `YouTube isteği başarısız (${status}): ${providerMessage}`
                                                                                                                                                                                                  : `YouTube isteği başarısız (${status}).`;
                                                                                                                                                                                                  }

                                                                                                                                                                                                  export async function fetchYoutubePlaylistPage({
                                                                                                                                                                                                    playlistId,
                                                                                                                                                                                                      apiKey,
                                                                                                                                                                                                        maxResults = 20,
                                                                                                                                                                                                          pageToken
                                                                                                                                                                                                          }: {
                                                                                                                                                                                                            playlistId: string;
                                                                                                                                                                                                              apiKey?: string;
                                                                                                                                                                                                                maxResults?: number;
                                                                                                                                                                                                                  pageToken?: string | null;
                                                                                                                                                                                                                  }) {
                                                                                                                                                                                                                    const cleanPlaylistId = extractYoutubePlaylistId(playlistId);
                                                                                                                                                                                                                      const cleanKey = apiKey?.trim();

                                                                                                                                                                                                                        if (!cleanPlaylistId) {
                                                                                                                                                                                                                            return { ok: false as const, message: 'YouTube playlist ID veya URL gerekli.' };
                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                if (!cleanKey || cleanKey === 'YOUR_YOUTUBE_API_KEY') {
                                                                                                                                                                                                                                    return { ok: false as const, message: 'YOUTUBE_API_KEY env eksik veya placeholder bırakılmış.' };
                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                        const safeMax = Math.min(Math.max(Number(maxResults) || 20, 1), 50);

                                                                                                                                                                                                                                          const url = new URL('https://www.googleapis.com/youtube/v3/playlistItems');
                                                                                                                                                                                                                                            url.searchParams.set('key', cleanKey);
                                                                                                                                                                                                                                              url.searchParams.set('part', 'snippet');
                                                                                                                                                                                                                                                url.searchParams.set('playlistId', cleanPlaylistId);
                                                                                                                                                                                                                                                  url.searchParams.set('maxResults', String(safeMax));

                                                                                                                                                                                                                                                    if (pageToken) {
                                                                                                                                                                                                                                                        url.searchParams.set('pageToken', pageToken);
                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                const response = await fetch(url.toString(), {
                                                                                                                                                                                                                                                                      cache: 'no-store',
                                                                                                                                                                                                                                                                            headers: {
                                                                                                                                                                                                                                                                                    Accept: 'application/json',
                                                                                                                                                                                                                                                                                            'User-Agent': 'Hayatimiz-Oyun-Admin/0.0.4'
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                          const payload = await response.json().catch(() => null);

                                                                                                                                                                                                                                                                                                              if (!response.ok) {
                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                            ok: false as const,
                                                                                                                                                                                                                                                                                                                                    message: youtubeErrorMessage(response.status, payload),
                                                                                                                                                                                                                                                                                                                                            status: response.status
                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                          const videos: YoutubePlaylistVideo[] = ((payload?.items ?? []) as YouTubePlaylistItem[]).map((item, index) => {
                                                                                                                                                                                                                                                                                                                                                                const videoId = item.snippet?.resourceId?.videoId ?? '';

                                                                                                                                                                                                                                                                                                                                                                      return {
                                                                                                                                                                                                                                                                                                                                                                              order: index + 1,
                                                                                                                                                                                                                                                                                                                                                                                      videoId,
                                                                                                                                                                                                                                                                                                                                                                                              title: item.snippet?.title ?? 'İsimsiz Video',
                                                                                                                                                                                                                                                                                                                                                                                                      description: item.snippet?.description ?? '',
                                                                                                                                                                                                                                                                                                                                                                                                              publishedAt: item.snippet?.publishedAt ?? null,
                                                                                                                                                                                                                                                                                                                                                                                                                      thumbnailUrl: getBestThumbnail(item),
                                                                                                                                                                                                                                                                                                                                                                                                                              url: videoId ? `https://www.youtube.com/watch?v=${videoId}` : ''
                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ok: true as const,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        playlistId: cleanPlaylistId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                              count: videos.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    videos,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          nextPageToken: typeof payload?.nextPageToken === 'string' ? payload.nextPageToken : null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ok: false as const,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message: error instanceof Error ? `YouTube bağlantı hatası: ${error.message}` : 'YouTube bağlantı hatası oluştu.'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export async function fetchYoutubePlaylistAll({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        playlistId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          apiKey,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            maxPages = 4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              playlistId: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                apiKey?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  maxPages?: number;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const allVideos: YoutubePlaylistVideo[] = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      let nextPageToken: string | null = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let cleanPlaylistId = extractYoutubePlaylistId(playlistId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          for (let page = 0; page < maxPages; page += 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const result = await fetchYoutubePlaylistPage({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    playlistId: cleanPlaylistId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          apiKey,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                maxResults: 50,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pageToken: nextPageToken
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!result.ok) return result;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cleanPlaylistId = result.playlistId;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      allVideos.push(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...result.videos.map((video) => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...video,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            order: allVideos.length + video.order
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          nextPageToken = result.nextPageToken;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!nextPageToken) break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ok: true as const,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          playlistId: cleanPlaylistId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              count: allVideos.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  videos: allVideos,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      nextPageToken
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
}